name: "Sphinx: Render docs"

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
        # Step 1: Run custom Bash commands
    - name: Run pre-setup commands
      run: |
        echo "Running pre-setup commands..."
        sudo apt-get update
        python -m pip install --upgrade pip
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'  # Specify your desired Python version
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
    - name: Upgrade pip, install package, install requirements, build docs
      run: |
        pip install --upgrade pip
        pip install .
        pip install -r ./docs/requirements.txt
        pip install sphinx
        ls
        cd docs
        make html
    # sphinx-build docs ./docs/_build/html/
    # - name: Build HTML
    #   uses: ammaraskar/sphinx-action@master
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: html-docs
        path: docs/build/html/
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/build/html